// =============================================================================
// Core Types
// =============================================================================

export type UserRole = 'member' | 'treasurer' | 'secretary' | 'organizer' | 'admin'

export type DocumentCategory = 'agreements' | 'minutes' | 'financial' | 'policies' | 'forms'

export type DocumentVisibility = 'all_members' | 'organizers_only' | 'owner_only'

export type ActivityType = 'document_uploaded' | 'document_acknowledged' | 'document_signed' | 'document_updated' | 'document_deleted' | 'auto_generated'

// =============================================================================
// User Types
// =============================================================================

export interface User {
  id: string
  name: string
  email: string
  avatar: string | null
  role: UserRole
}

export interface UserReference {
  id: string
  name: string
  avatar?: string | null
}

// =============================================================================
// Circle Types
// =============================================================================

export interface Circle {
  id: string
  name: string
  memberCount: number
}

export interface RetentionPolicy {
  enabled: boolean
  archiveAfterDays: number | null
  deleteAfterDays: number | null
}

export interface CircleDocumentSpace {
  id: string
  circleId: string
  circleName: string
  totalDocuments: number
  storageUsedBytes: number
  storageQuotaBytes: number
  categories: DocumentCategory[]
  retentionPolicy: RetentionPolicy
  lastActivityAt: string
}

// =============================================================================
// Folder Types
// =============================================================================

export interface Folder {
  id: string
  name: string
  circleId: string
  parentId: string | null
  documentCount: number
  icon: string
  color: string
  createdAt: string
}

// =============================================================================
// Document Types
// =============================================================================

export interface DocumentPermissions {
  visibility: DocumentVisibility
  canDownload: boolean
  canComment: boolean
}

export interface Document {
  id: string
  title: string
  description: string
  fileName: string
  fileUrl: string
  mimeType: string
  fileSize: number
  folderId: string
  circleId: string
  category: DocumentCategory
  tags: string[]
  uploadedBy: UserReference
  permissions: DocumentPermissions
  requiresAcknowledgment: boolean
  requiresSignature: boolean
  acknowledgmentCount?: number
  signatureCount?: number
  totalMembers?: number
  currentVersion: number
  isStarred: boolean
  isArchived: boolean
  isAutoGenerated?: boolean
  isDraft?: boolean
  createdAt: string
  updatedAt: string
}

// =============================================================================
// Document Template Types
// =============================================================================

export interface DocumentTemplate {
  id: string
  name: string
  description: string
  category: DocumentCategory | 'forms'
  fileUrl: string
  mimeType: string
  fileSize: number
  fields: string[]
  usageCount: number
  isDefault: boolean
  createdBy: UserReference
  createdAt: string
  updatedAt: string
}

// =============================================================================
// Document Version Types
// =============================================================================

export interface DocumentVersion {
  id: string
  documentId: string
  versionNumber: number
  fileName: string
  fileUrl: string
  fileSize: number
  changeDescription: string
  uploadedBy: UserReference
  createdAt: string
}

// =============================================================================
// Document Acknowledgment Types
// =============================================================================

export interface DocumentAcknowledgment {
  id: string
  documentId: string
  userId: string
  userName: string
  userAvatar: string | null
  acknowledgedAt: string
}

// =============================================================================
// Document Signature Types
// =============================================================================

export interface DocumentSignature {
  id: string
  documentId: string
  userId: string
  userName: string
  userEmail: string
  signatureImageUrl: string
  ipAddress: string
  userAgent: string
  signedAt: string
}

// =============================================================================
// Activity Types
// =============================================================================

export interface RecentActivity {
  id: string
  type: ActivityType
  documentId: string
  documentTitle: string
  userId: string
  userName: string
  userAvatar: string | null
  circleName: string
  timestamp: string
}

// =============================================================================
// Storage Stats Types
// =============================================================================

export interface CategoryStats {
  count: number
  sizeBytes: number
}

export interface StorageStats {
  totalUsedBytes: number
  totalQuotaBytes: number
  documentCount: number
  folderCount: number
  byCategory: Record<string, CategoryStats>
  byFileType: Record<string, CategoryStats>
}

// =============================================================================
// Component Props - Document Library
// =============================================================================

export interface DocumentLibraryProps {
  /** All documents to display */
  documents: Document[]
  /** Folder structure for navigation */
  folders: Folder[]
  /** Circle document spaces for storage info */
  circleDocumentSpaces: CircleDocumentSpace[]
  /** Recent activity feed */
  recentActivity: RecentActivity[]
  /** Storage statistics */
  storageStats: StorageStats
  /** Currently selected folder ID */
  selectedFolderId?: string | null
  /** Currently selected circle ID */
  selectedCircleId?: string | null
  /** Current view mode */
  viewMode?: 'grid' | 'list'
  /** Current search query */
  searchQuery?: string
  /** Called when user clicks on a document */
  onDocumentClick?: (document: Document) => void
  /** Called when user wants to download a document */
  onDownload?: (document: Document) => void
  /** Called when user wants to delete a document */
  onDelete?: (documentId: string) => void
  /** Called when user wants to star/unstar a document */
  onToggleStar?: (documentId: string) => void
  /** Called when user selects a folder */
  onFolderSelect?: (folderId: string | null) => void
  /** Called when user selects a circle */
  onCircleSelect?: (circleId: string | null) => void
  /** Called when user changes view mode */
  onViewModeChange?: (mode: 'grid' | 'list') => void
  /** Called when user updates search query */
  onSearch?: (query: string) => void
  /** Called when user wants to upload a new document */
  onUpload?: () => void
  /** Called when user wants to create a new folder */
  onCreateFolder?: () => void
}

// =============================================================================
// Component Props - Circle Documents
// =============================================================================

export interface CircleDocumentsProps {
  /** Documents for the selected circle */
  documents: Document[]
  /** Folders in this circle */
  folders: Folder[]
  /** Circle document space info */
  documentSpace: CircleDocumentSpace
  /** Circle info */
  circle: Circle
  /** Currently selected category filter */
  selectedCategory?: DocumentCategory | 'all'
  /** Called when user clicks on a document */
  onDocumentClick?: (document: Document) => void
  /** Called when user wants to download a document */
  onDownload?: (document: Document) => void
  /** Called when user selects a category */
  onCategorySelect?: (category: DocumentCategory | 'all') => void
  /** Called when user wants to upload a document */
  onUpload?: () => void
  /** Called when user wants to manage retention policy */
  onManageRetention?: () => void
}

// =============================================================================
// Component Props - Document Viewer
// =============================================================================

export interface DocumentViewerProps {
  /** Document to display */
  document: Document
  /** Version history for the document */
  versions: DocumentVersion[]
  /** Acknowledgments for the document */
  acknowledgments: DocumentAcknowledgment[]
  /** Signatures for the document */
  signatures: DocumentSignature[]
  /** Current user ID for determining actions */
  currentUserId: string
  /** Whether current user has acknowledged */
  hasAcknowledged?: boolean
  /** Whether current user has signed */
  hasSigned?: boolean
  /** Called when user wants to download */
  onDownload?: () => void
  /** Called when user wants to share */
  onShare?: () => void
  /** Called when user acknowledges the document */
  onAcknowledge?: () => void
  /** Called when user wants to sign the document */
  onSign?: () => void
  /** Called when user wants to view a specific version */
  onViewVersion?: (versionId: string) => void
  /** Called when user wants to restore a version */
  onRestoreVersion?: (versionId: string) => void
  /** Called when user wants to edit the document */
  onEdit?: () => void
  /** Called when user wants to delete the document */
  onDelete?: () => void
  /** Called to go back to document list */
  onBack?: () => void
}

// =============================================================================
// Component Props - Document Upload
// =============================================================================

export interface DocumentUploadProps {
  /** Available circles to upload to */
  circles: Circle[]
  /** Available folders for organization */
  folders: Folder[]
  /** Available templates to create from */
  templates: DocumentTemplate[]
  /** Pre-selected circle ID */
  selectedCircleId?: string
  /** Pre-selected folder ID */
  selectedFolderId?: string
  /** Called when upload is submitted */
  onUpload?: (data: DocumentUploadData) => void
  /** Called when user cancels upload */
  onCancel?: () => void
  /** Called when user wants to create from template */
  onUseTemplate?: (templateId: string) => void
}

export interface DocumentUploadData {
  file: File
  title: string
  description: string
  circleId: string
  folderId: string
  category: DocumentCategory
  tags: string[]
  visibility: DocumentVisibility
  requiresAcknowledgment: boolean
  requiresSignature: boolean
}

// =============================================================================
// Component Props - Document Templates
// =============================================================================

export interface DocumentTemplatesProps {
  /** Available templates */
  templates: DocumentTemplate[]
  /** Selected category filter */
  selectedCategory?: DocumentCategory | 'forms' | 'all'
  /** Called when user selects a template to use */
  onUseTemplate?: (template: DocumentTemplate) => void
  /** Called when user wants to edit a template */
  onEditTemplate?: (templateId: string) => void
  /** Called when user wants to delete a template */
  onDeleteTemplate?: (templateId: string) => void
  /** Called when user wants to create a new template */
  onCreateTemplate?: () => void
  /** Called when user changes category filter */
  onCategorySelect?: (category: DocumentCategory | 'forms' | 'all') => void
}

// =============================================================================
// Component Props - Agreement Signing
// =============================================================================

export interface AgreementSigningProps {
  /** Document to sign */
  document: Document
  /** Current user info */
  currentUser: User
  /** Existing signatures on the document */
  signatures: DocumentSignature[]
  /** Called when user completes signing */
  onSign?: (signatureData: SignatureData) => void
  /** Called when user cancels signing */
  onCancel?: () => void
  /** Called when user wants to download unsigned document */
  onDownload?: () => void
}

export interface SignatureData {
  signatureImageDataUrl: string
  agreedToTerms: boolean
}

// =============================================================================
// Component Props - Storage Management
// =============================================================================

export interface StorageManagementProps {
  /** Circle document spaces */
  circleDocumentSpaces: CircleDocumentSpace[]
  /** Overall storage stats */
  storageStats: StorageStats
  /** Called when user wants to manage a circle's storage */
  onManageCircleStorage?: (circleId: string) => void
  /** Called when user wants to update retention policy */
  onUpdateRetention?: (circleId: string, policy: RetentionPolicy) => void
  /** Called when user wants to archive old documents */
  onArchiveOld?: (circleId: string) => void
  /** Called when user wants to request more storage */
  onRequestStorage?: () => void
}
